# Generated by Django 4.0.4 on 2022-05-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0002_marque_delete_livre'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='marque_voiture',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
