# Generated by Django 4.0.4 on 2022-05-11 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0003_voiture_marque_voiture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='marque_voiture',
        ),
        migrations.AddField(
            model_name='voiture',
            name='marque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marque', to='myfirstapp.marque'),
        ),
    ]
